language: java
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_URL="https://mirror.racket-lang.org/installers/6.6/racket-6.6-x86_64-linux.sh"

before_install:
  - if [[ ! -e "$RACKET_DIR/bin/racket" ]]; then
      rm -rf $RACKET_DIR;
      curl -L -o racket.sh $RACKET_URL;
      sh ./racket.sh --in-place --dest $RACKET_DIR;
    else echo "using racket from cache"; fi
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install: 
  - raco pkg install

script:
  - raco test 
  - time raco make test/all-rosette-tests.rkt
  - raco test test/all-rosette-tests.rkt
  - time raco make test/all-sdsl-tests.rkt
  - raco test test/all-sdsl-tests.rkt

cache:
  directories:
    - $RACKET_DIR
